# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windows.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 403)
        self.data = QtWidgets.QLabel(Form)
        self.data.setGeometry(QtCore.QRect(30, 30, 101, 16))
        self.data.setObjectName("data")
        self.base = QtWidgets.QLabel(Form)
        self.base.setGeometry(QtCore.QRect(30, 70, 101, 16))
        self.base.setObjectName("base")
        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setGeometry(QtCore.QRect(180, 360, 193, 28))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(30, 110, 331, 191))
        self.tabWidget.setMinimumSize(QtCore.QSize(331, 0))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.checkBox = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.checkBox.setGeometry(QtCore.QRect(20, 20, 91, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 60, 91, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 100, 91, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.checkBox_4.setGeometry(QtCore.QRect(180, 20, 91, 19))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.checkBox_5.setGeometry(QtCore.QRect(180, 60, 141, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.tabWidgetPage1)
        self.checkBox_6.setGeometry(QtCore.QRect(180, 100, 91, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.print_logo = QtWidgets.QTextEdit(self.tabWidgetPage2)
        self.print_logo.setGeometry(QtCore.QRect(3, 6, 321, 161))
        self.print_logo.setObjectName("print_logo")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.dzxml = QtWidgets.QRadioButton(Form)
        self.dzxml.setGeometry(QtCore.QRect(40, 320, 115, 19))
        self.dzxml.setObjectName("dzxml")
        self.ptxml = QtWidgets.QRadioButton(Form)
        self.ptxml.setGeometry(QtCore.QRect(210, 320, 115, 19))
        self.ptxml.setAcceptDrops(False)
        self.ptxml.setCheckable(True)
        self.ptxml.setChecked(True)
        self.ptxml.setObjectName("ptxml")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(310, 30, 47, 21))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Form)
        self.toolButton_2.setGeometry(QtCore.QRect(310, 70, 47, 21))
        self.toolButton_2.setObjectName("toolButton_2")
        self.date_file = QtWidgets.QLineEdit(Form)
        self.date_file.setGeometry(QtCore.QRect(130, 30, 171, 21))
        self.date_file.setObjectName("date_file")
        self.base_file = QtWidgets.QLineEdit(Form)
        self.base_file.setGeometry(QtCore.QRect(130, 70, 171, 21))
        self.base_file.setObjectName("base_file")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.data.setText(_translate("Form", "选择数据文件"))
        self.base.setText(_translate("Form", "选择基础文件"))
        self.tabWidget.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.checkBox.setText(_translate("Form", "提运单号"))
        self.checkBox_2.setText(_translate("Form", "目的地"))
        self.checkBox_3.setText(_translate("Form", "出口口岸"))
        self.checkBox_4.setText(_translate("Form", "汇率"))
        self.checkBox_5.setText(_translate("Form", "加工贸易手册号"))
        self.checkBox_6.setText(_translate("Form", "装船口岸"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("Form", "选持备注内容"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("Form", "生成过程中报错"))
        self.dzxml.setText(_translate("Form", "电子发票"))
        self.ptxml.setText(_translate("Form", "普通发票"))
        self.toolButton.setText(_translate("Form", "..."))
        self.toolButton_2.setText(_translate("Form", "..."))

